using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SimpleSerializer;

namespace SimpleSerializerTest
{
    [TestClass]
    public class JsonSerializerTest
    {
        [TestMethod]
        public void SerializeTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void DeserializeTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}