using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using inner;

namespace innerTest
{
    [TestClass]
    public class BarClassTest
    {
        [TestMethod]
        public void MyPublicMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void MyPublicMethodTest1()
        {
            Assert.Fail("autogenerated");
        }
    }
}