using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Two;

namespace TwoTest
{
    [TestClass]
    public class FooClassTest
    {
        [TestMethod]
        public void MyPublicMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}